<?php
/**
 * ONE-TIME SETUP SCRIPT
 * ─────────────────────────────────────────────────────────────────────────
 * 1. Open this file in your browser (e.g. http://localhost/pulsefit_site/setup.php)
 * 2. It will compute SHA-256(salt + password) and write it into data/admin.php
 * 3. DELETE this file immediately after running it — it contains the plain password!
 * ─────────────────────────────────────────────────────────────────────────
 */

$salt       = 'pf9x#2025$salt';
$plain_pass = 'PulseFit@2025';

// Compute the SHA-256 message digest
$hash = hash('sha256', $salt . $plain_pass);

// Build the new data/admin.php content (no plain password stored)
$contents  = "<?php\n";
$contents .= "// Admin credentials — auto-generated by setup.php\n";
$contents .= "// The plain-text password is NEVER stored here; only its SHA-256 hash.\n";
$contents .= "define('ADMIN_USER', " . var_export('admin', true) . ");\n";
$contents .= "define('ADMIN_SALT', " . var_export($salt, true) . ");\n";
$contents .= "define('ADMIN_HASH', " . var_export($hash, true) . ");\n";

$path = __DIR__ . '/data/admin.php';

if (file_put_contents($path, $contents) !== false) {
    echo '<!DOCTYPE html><html><body style="font-family:monospace;padding:40px;">';
    echo '<h2 style="color:green;">Setup complete!</h2>';
    echo '<p><strong>data/admin.php</strong> has been written.</p>';
    echo '<p>Algorithm: <strong>SHA-256</strong></p>';
    echo '<p>Salt: <strong>' . htmlspecialchars($salt) . '</strong></p>';
    echo '<p>Stored hash: <strong>' . htmlspecialchars($hash) . '</strong></p>';
    echo '<p style="color:red;font-size:1.1em;"><strong>IMPORTANT: Delete setup.php now!</strong><br>';
    echo 'It contains the plain-text password and must not remain on the server.</p>';
    echo '<p><a href="login.php">Go to Login</a></p>';
    echo '</body></html>';
} else {
    http_response_code(500);
    echo '<!DOCTYPE html><html><body style="font-family:monospace;padding:40px;">';
    echo '<h2 style="color:red;">Setup failed!</h2>';
    echo '<p>Could not write to <strong>data/admin.php</strong>. Check file/folder permissions.</p>';
    echo '</body></html>';
}
