<?php
// Admin credentials — auto-generated by setup.php
// The plain-text password is NEVER stored here; only its SHA-256 hash.
define('ADMIN_USER', 'admin');
define('ADMIN_SALT', 'pf9x#2025$salt');
define('ADMIN_HASH', 'b91852555e047afaedcdb809dfda66b532ed1d88ad28e7004d48ead3eaac960f');
